local header_lines = {
	{
		[[                    ___====-_  _-====___                      ]],
		[[              _--^^^#####//      \\#####^^^--_                ]],
		[[           _-^##########// (    ) \\##########^-_             ]],
		[[          -############//  |\^^/|  \\############-            ]],
		[[        _/############//   (@::@)   \\############\_          ]],
		[[       /#############((     \\//     ))#############\         ]],
		[[      -###############\\    (oo)    //###############-        ]],
		[[     -#################\\  / "" \  //#################-       ]],
		[[    -###################\\/  ()  \//###################-      ]],
		[[   _#/|##########/\######(   ()   )######/\##########|\#_     ]],
		[[   |/ |#/\#/\#/\/  \#/\##\  ()  /##/\#/  \/\/#/\#/\| \|      ]],
		[[       |/  v  v      v  \#\| () |/#/  v      v  v  \|        ]],
		[[                      `\/   \/      \/   \/'                  ]],
		[[]],
		[[A dragon does not fear the storm. It rises with the wind, embraces the fire, and soars above the clouds. Be the dragon—unyielding, fierce, and unstoppable.]],
	},
	{
		[[██╗  ██╗ █████╗ ██╗███████╗███████╗███╗   ██╗]],
		[[██║ ██╔╝██╔══██╗██║╚══███╔╝██╔════╝████╗  ██║]],
		[[█████╔╝ ███████║██║  ███╔╝ █████╗  ██╔██╗ ██║]],
		[[██╔═██╗ ██╔══██║██║ ███╔╝  ██╔══╝  ██║╚██╗██║]],
		[[██║  ██╗██║  ██║██║███████╗███████╗██║ ╚████║]],
		[[╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚═╝  ╚═══╝]],
		[[]],
		[[Continuous improvement is the key to success. start through small, consistent steps.]],
		[[]],
	},
	{
		[[██╗██╗  ██╗██╗ ██████╗  █████╗ ██╗]],
		[[██║██║ ██╔╝██║██╔════╝ ██╔══██╗██║]],
		[[██║█████╔╝ ██║██║  ███╗███████║██║]],
		[[██║██╔═██╗ ██║██║   ██║██╔══██║██║]],
		[[██║██║  ██╗██║╚██████╔╝██║  ██║██║]],
		[[╚═╝╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝]],
		[[Concept of finding purpose in life by aligning your passion, skills, societal needs, and potential for income.]],
	},

	-- {
	-- 	[[          ,~-.                            ]],
	-- 	[[         (  ' )-.          ,~'`-.         ]],
	-- 	[[      ,~' `  ' ) )       _(   _) )        ]],
	-- 	[[     ( ( .--.===.--.    (  `    ' )       ]],
	-- 	[[      `.%%.;::|888.#`.   `-'`~~=~'        ]],
	-- 	[[      /%%/::::|8888\##\                   ]],
	-- 	[[     |%%/:::::|88888\##|                  ]],
	-- 	[[     |%%|:::::|88888|##|.,-.              ]],
	-- 	[[     \%%|:::::|88888|##/    )_            ]],
	-- 	[[      \%\:::::|88888/#/ ( `'  )           ]],
	-- 	[[       \%\::::|8888/#/(  ,  -'`-.         ]],
	-- 	[[   ,~-. `%\:::|888/#'(  (     ') )        ]],
	-- 	[[  (  ) )_ `\__|__/'   `~-~=--~~='         ]],
	-- 	[[ ( ` ')  ) [VVVVV]                        ]],
	-- 	[[(_(_.~~~'   \|_|/                         ]],
	-- 	[[            [XXX]                         ]],
	-- 	[[            `"""'                         ]],
	-- 	[[                                          ]],
	-- 	[[Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.]],
	-- },
}

local motivational_quotes = {
	[[The only way to do great work is to love what you do. – Steve Jobs]],
	[[Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer]],
	[[Don’t watch the clock; do what it does. Keep going. – Sam Levenson]],
	[[Believe you can and you're halfway there. – Theodore Roosevelt]],
	[[The future depends on what you do today. – Mahatma Gandhi]],
	[[It always seems impossible until it's done. – Nelson Mandela]],
	[[Opportunities don't happen, you create them. – Chris Grosser]],
	[[Success is the sum of small efforts, repeated day in and day out. – Robert Collier]],
	[[The best way to predict the future is to create it. – Peter Drucker]],
	[[You are never too old to set another goal or to dream a new dream. – C.S. Lewis]],
	[[Act as if what you do makes a difference. It does. – William James]],
	[[Start where you are. Use what you have. Do what you can. – Arthur Ashe]],
	[[The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt]],
	[[Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis]],
	[[Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau]],
	[[If you can dream it, you can do it. – Walt Disney]],
	[[You miss 100% of the shots you don’t take. – Wayne Gretzky]],
	[[The way to get started is to quit talking and begin doing. – Walt Disney]],
	[[I am not a product of my circumstances. I am a product of my decisions. – Stephen Covey]],
	[[Everything you’ve ever wanted is on the other side of fear. – George Addair]],
}

return { header = header_lines, footer = motivational_quotes }
